apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: matrikkel-geoserver
  namespace: "{{ namespace }}"
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
    - "{{ ingress }}"
  replicas: 0
#    min: {{ replicasMin:-2 }}
#    max: {{ replicasMax:-4 }}

  resources:
    requests:
      cpu: {{cpuRequest:-100m}}
      memory: {{memoryRequest:-4G}}
    limits:
      memory: {{memoryLimit:-6G}}

  liveness:
    port: 8602
    path: /health
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8602
    path: /health
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3

  accessPolicy:
    inbound:
      rules:
        - application: "matrikkelproxy"
    outbound:
      external:
        - host: "{{ keycloakHost }}"

  databases:
    - name: "{{ databaseName }}"
      envName: JDBC_URL

  env:
    - name: PROXY_BASE_URL
      value: "https://{{ publicHost }}/geoservergeo"
    - name: JAVA_OPTS
      value: "-DALLOW_ENV_PARAMETRIZATION=true"
    - name: GEOSERVER_GEOJSON_LEGACY_CRS
      value: "true"
    - name: KART_DB_SCHEMA
      gsmSecretName: "{{ gsmDbPrefix }}-geoserver-db-username"
    - name: KART_DB_USERNAME
      gsmSecretName: "{{ gsmDbPrefix }}-geoserver-db-username"
    - name: KART_DB_PASSWORD
      gsmSecretName: "{{ gsmDbPrefix }}-geoserver-db-password"

  extraContainers:
    - image: "{{ auth-proxy-image }}"
      name: matrikkel-geoserver-auth-proxy
      additionalPorts:
        - name: auth-proxy
          port: 8602
          protocol: TCP
      ingressPort: 8602
      resources:
        requests:
          cpu: 100m
          memory: 128M
        limits:
          memory: 512M
      env:
        - name: KEYCLOAK_ISSUER_URL
          value: "https://{{ keycloakHost }}/auth/realms/{{ keycloakRealm }}"
        - name: KEYCLOAK_CLIENT_ID
          value: "matrikkel-token-exchange"
        - name: ACCEPTED_AUDIENCES
          value: "matrikkel-geoserver"
        - name: GEOSERVER_URL
          value: "http://localhost:8080"
        - name: HEALTH_ENDPOINT
          value: "/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities"
        - name: PORT
          value: "8602"
