apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: matrikkel-geoserver
  namespace: matrikkel-main
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
    - matrikkel-geoserver.atkv3-dev.kartverket-intern.cloud
  replicas: 1

  resources:
    requests:
      cpu: 100m
      memory: 1G
    limits:
      memory: 2G

  liveness:
    port: 8602
    path: /health
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8602
    path: /health
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3

#  Denne burde ha vært her. Men av en eller annen grunn fungerer det uten.
#  Dette har blitt nevnt på #gen-skip
#  accessPolicy:
#    outbound:
#      external:
#        - host: "kc-test.matrikkel.no"

  databases:
    - name: matrikkel-devtest
      fields:
        - envName: KART_DB_HOST
          path: host
        - envName: KART_DB_PORT
          path: ports[0].port

  env:
    - name: JAVA_OPTS
      value: "-DALLOW_ENV_PARAMETRIZATION=true"
    - name: GEOSERVER_GEOJSON_LEGACY_CRS
      value: "true"
    - name: KART_DB_DATABASE
      value: "MA02TST.STATKART.NO"
    - name: KART_DB_SCHEMA
      value: "DEVTEST_KART"
    - name: KART_DB_USERNAME
      value: "DEVTEST_KART"
    - name: KART_DB_PASSWORD
      gsmSecretName: "dev-matrikkel-geoserver-db-user-password"

  extraContainers:
    - image: "{{ auth-proxy-image }}"
      name: matrikkel-geoserver-auth-proxy
      additionalPorts:
        - name: auth-proxy
          port: 8602
          protocol: TCP
      ingressPort: 8602
      env:
        - name: KEYCLOAK_ISSUER_URL
          value: "https://kc-test.matrikkel.no/auth/realms/matrikkelen-test"
        - name: KEYCLOAK_CLIENT_ID
          value: "matrikkel-token-exchange"
        - name: ACCEPTED_AUDIENCES
          value: "matrikkel-geoserver"
        - name: GEOSERVER_URL
          value: "http://localhost:8080"
        - name: HEALTH_ENDPOINT
          value: /geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png
        - name: PORT
          value: "8602"