version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/auth-proxy"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "/app"
      - "/auth-proxy"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "geoserver"
        versions:
          - "3.1.x" # Blocks nightly tags; Update this when upgrading GeoServer
          - "4.0.x" # Blocks nightly tags; Update this when upgrading GeoServer
