version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "geoserver"
        versions:
          - "*.x"          # Blocks 3.1.x, 3.2.x, etc. These are nightly builds