services:
  geoserver:
    image: docker.osgeo.org/geoserver:3.0.0
    ports:
    - "8087:8080"
    volumes:
      - ./app/src/main/resources/data:/opt/geoserver_data
    env_file:
      - docker/local-compose.env
    environment:
      - SKIP_DEMO_DATA=true
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=oracle
      - JAVA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
