services:
  geoserver:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
    - "8087:8080"
    env_file:
      - docker/local-compose.env
    environment:
      - SKIP_DEMO_DATA=true
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=oracle
      - JAVA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
