namespace: matrikkel-main
ingress: matrikkel-geoserver.atkv3-dev.kartverket-intern.cloud
publicHost: matrikkel.atkv3-dev.kartverket-intern.cloud

# Scaling down dev environment
replicasMin: 1
replicasMax: 1
cpuRequest: 100m
memoryRequest: 1G
memoryLimit: 2G

keycloakHost: kc-test.matrikkel.no
keycloakRealm: matrikkelen-test
databaseName: matrikkel-devtest
gsmDbPrefix: matrikkel-dev