namespace: matrikkel-nd
ingress: matrikkel-geoserver-nd.atkv3-prod.kartverket-intern.cloud
publicHost: nd.matrikkel.no

# Skalerer opp litt i produksjon
replicasMax: 6
cpuRequest: 500m

keycloakHost: auth.matrikkel.no
keycloakRealm: matrikkelen-prod

databaseName: matrikkel-prod-readonly
gsmDbPrefix: matrikkel-innsyn